<%@ Page Title="Create User Page" Language="C#" MasterPageFile="~/Admin/Admin.Master" AutoEventWireup="true" CodeBehind="Useradmin.aspx.cs" Inherits="ARC.Admin.Useradmin" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder3" runat="server">
    <div align="center">
        <asp:Label ID="Label1" runat="server" Text="Create New User Page" Font-Size="X-Large" 
            Font-Bold="True"></asp:Label>
    </div>
    <div>
        <table width="100%">
            <tr>
                <td>
                </td>
                <td align="right">
                    <h3 class="span_font_h3" style="font-weight: normal">Welcome </h3>
                </td>
                <td align="right" width="5%">
                    <asp:LoginName ID="LoginName1" runat="server" CssClass="span_font_h3" />
                </td>
                <td style="padding-left: 15px" width="20%">
                    <asp:LoginStatus ID="LoginStatus1" runat="server" 
                        LogoutPageUrl="~/Default.aspx" CssClass="span_font_h3" 
                        LogoutAction="Redirect" />
                </td>
            </tr>
        </table>
    </div>
    <br />
    <br />
    <div align="center">
        <asp:Panel ID="Panel1" runat="server">
            <asp:CreateUserWizard ID="CreateUserWizard1" runat="server" 
                AnswerLabelText="&lt;h3&gt;Security Answer:&lt;/h3&gt;" 
                CompleteSuccessText="&lt;h3&gt;Your account has been successfully created.&lt;/h3&gt;" 
                ConfirmPasswordLabelText="&lt;h3&gt;Confirm Password:&lt;/h3&gt;" 
                EmailLabelText="&lt;h3&gt;E-mail:&lt;/h3&gt;" 
                PasswordLabelText="&lt;h3&gt;Password:&lt;/h3&gt;" 
                QuestionLabelText="&lt;h3&gt;Security Question:&lt;/h3&gt;" 
                UserNameLabelText="&lt;h3&gt;User Name:&lt;/h3&gt;" 
                DisplayCancelButton="True" LoginCreatedUser="False" 
                FinishPreviousButtonText="" OnCancelButtonClick="CreateUserWizard1_OnCancelButtonClick">
                <WizardSteps>
                    <asp:CreateUserWizardStep ID="CreateUserWizardStep1" runat="server" 
                        Title="&lt;h3&gt;Create A New User&lt;/h3&gt;&lt;br/&gt;">
                    </asp:CreateUserWizardStep>
                    <asp:CompleteWizardStep ID="CompleteWizardStep1" runat="server" 
                        Title="&lt;h3&gt;Complete&lt;/h3&gt;">
                        <ContentTemplate>
                            <table border="0">
                                <tr>
                                    <td align="center" colspan="2">
                                        <h3>
                                            Complete</h3>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <h3>
                                            Your account has been successfully created.</h3>
                                    </td>
                                </tr>
                                <tr>
                                    <td align="right" colspan="2">
                                        <asp:Button ID="ContinueButton" runat="server" CausesValidation="False" 
                                            CommandName="Continue" Text="Continue" ValidationGroup="CreateUserWizard1" OnClick="ContinueButton_OnClick" />
                                    </td>
                                </tr>
                            </table>
                        </ContentTemplate>
                    </asp:CompleteWizardStep>
                </WizardSteps>
            </asp:CreateUserWizard>
        </asp:Panel>        
        <br />
        <br />
        <br />
        <asp:Panel ID="Panel2" runat="server">
            <h3>To modify an existing user, <asp:LinkButton ID="LinkButton1" runat="server" CssClass="yellow-text-underline" Font-Size="Small" onclick="LinkButton1_Click">Click Here.</asp:LinkButton></h3>
        </asp:Panel>
        <div>
            <asp:GridView ID="GridView1" 
                runat="server" 
                AutoGenerateColumns="False" 
                AutoGenerateDeleteButton="True" 
                AutoGenerateEditButton="True" 
                OnRowDeleting="GridView1_OnRowDeleting"
                OnRowEditing="GridView1_OnRowEditing" 
                OnRowUpdating="GridView1_OnRowUpdating" 
                OnRowCancelingEdit="GridView1_RowCancelingEdit"
                Visible="False" >
                <columns>
                    <asp:boundfield datafield="UserName" headertext="UserName" ReadOnly="true" />
                    <asp:boundfield datafield="Email" headertext="Email" />                    
                    <asp:boundfield datafield="Comment" headertext="Comment" />
                    <asp:checkboxfield datafield="IsApproved" headertext="IsApproved" />
                    <asp:checkboxfield datafield="IsLockedOut" headertext="IsLockedOut" ReadOnly="true" />                    
                    <asp:boundfield datafield="CreationDate" headertext="CreationDate"  ReadOnly="true"/>
                    <asp:boundfield datafield="LastLoginDate" headertext="LastLoginDate" ReadOnly="true" />                                        
                    <asp:checkboxfield datafield="IsOnline" headertext="IsOnline" ReadOnly="true" />
                    <asp:CheckBoxField DataField="Admin" HeaderText="Admin" />
                    <asp:CheckBoxField DataField="PicUpdater" HeaderText="PicUpdater" />
                    <asp:CheckBoxField DataField="CalUpdater" HeaderText="CalUpdater" />
                    <asp:CheckBoxField DataField="NewsUpdater" HeaderText="NewsUpdater" />                    
                </columns>
            </asp:GridView>
        </div>
        <br />
        <br />
        <br />
        <asp:HyperLink ID="HyperLink1" runat="server" CssClass="yellow-text-underline" NavigateUrl="~/Admin/tools.aspx">Back to Admin Tools Page</asp:HyperLink>
    </div>
</asp:Content>
