<%@ Page Title="eNewsletter Modify" Language="C#" MasterPageFile="~/Admin/Admin.Master" AutoEventWireup="true" CodeBehind="eNewsletter_Modify.aspx.cs" Inherits="ARC.Admin.eNewsletter_Modify" %>


<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder3" runat="server">
    <br />
    <br />
    <div>
        <h1><asp:Label ID="Label1" runat="server" Text="eNewsletter Modify Tool"></asp:Label></h1>
    </div>
    <div>
        <table width="100%">
            <tr>
                <td>
                </td>
                <td align="right">
                    <h3 class="span_font_h3" style="font-weight: normal">Welcome </h3>
                </td>
                <td align="right" width="5%">
                    <asp:LoginName ID="LoginName1" runat="server" CssClass="span_font_h3" />
                </td>
                <td style="padding-left: 15px" width="20%">
                    <asp:LoginStatus ID="LoginStatus1" runat="server" 
                        LogoutPageUrl="~/Default.aspx" CssClass="span_font_h3" 
                        LogoutAction="Redirect" />
                </td>
            </tr>
        </table>
    </div>
    <br />
    <br />
    <div style="margin-left: 15px; margin-right: 15px;">
        <asp:GridView ID="GridView1" runat="server" 
            AllowPaging="True" 
            AllowSorting="True" 
            AutoGenerateColumns="False" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" 
            DataSourceID="SqlDataSource1"            
            Width="100%" 
            CellPadding="5" DataKeyNames="ID">
            <PagerSettings Mode="NumericFirstLast" />
            <RowStyle Font-Names="Tahoma,Arial" Font-Size="Medium" BackColor="#E4E4E4" 
                ForeColor="#1C4F81" />
            <EmptyDataRowStyle ForeColor="#184B7E" Font-Size="Medium" />
            <Columns>
                <asp:BoundField DataField="ID" HeaderText="ID" SortExpression="ID" ReadOnly="True" InsertVisible="False" ></asp:BoundField>
                <asp:BoundField DataField="Issue_Date" HeaderText="Issue_Date" SortExpression="Issue_Date" ReadOnly="false" ></asp:BoundField>
                <asp:BoundField DataField="File_Name" HeaderText="File_Name" SortExpression="File_Name" ></asp:BoundField>
                <asp:BoundField DataField="Excerpt" HeaderText="Excerpt" SortExpression="Excerpt" />
            </Columns>
            <PagerStyle HorizontalAlign="Center" ForeColor="Black" BackColor="#317BA4" />
            <HeaderStyle BackColor="#686868" ForeColor="White" />
            <AlternatingRowStyle Font-Names="Tahoma,Arial" 
                Font-Size="Medium" />
        </asp:GridView>
        <br />
        <br />
    </div>
    <br />
    <br />
    <asp:HyperLink ID="HyperLink1" runat="server" CssClass="yellow-text-underline" 
        Font-Size="Small" NavigateUrl="~/Admin/NewsAdmin/eNewletter_Update.aspx">Return to eNewsletter Update Tool</asp:HyperLink>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:Home_ARC_ORGConnectionString %>" 
        DeleteCommand="DELETE FROM eNewLetter WHERE ID=@ID;" 
        SelectCommand="SELECT ID, Issue_Date, [File_Name], Excerpt FROM eNewLetter ORDER BY Issue_Date DESC" 
        
        UpdateCommand="UPDATE eNewLetter SET Issue_Date=@Issue_Date, File_Name=@File_Name, Excerpt=@Excerpt WHERE ID=@ID;">
        <DeleteParameters>
            <asp:ControlParameter ControlID="GridView1" Name="ID" 
                PropertyName="SelectedDataKey" />
        </DeleteParameters>
        <UpdateParameters>
            <asp:Parameter Name="Issue_Date" />
            <asp:Parameter Name="File_Name" />
            <asp:Parameter Name="Excerpt" />
            <asp:Parameter Name="ID" />
        </UpdateParameters>
    </asp:SqlDataSource>
</asp:Content>
